README.md
=> please work

gatsby-browser.js, gatsby-ssr.js, package.json, src/components/forms/login.js, src/redux/ReduxWrapper.js, src/redux/reducers.js, src/redux/store.js
Added Redux / Redux Chrome devtools to project and example reducer function isLoggedIn - will need to be changed oncelogin routes are deployed from backend
Demoed functionality over zoom to other team members
=> ✨ Redux boiler plate added

.gitignore, gatsby-config.js, package.json, src/components/navbar.js, src/helpers.js, src/pages/users.js, yarn.lock
Login with oauth / view users once logged in
- [] Bug fix (non-breaking change which fixes an issue)
=> ✨ Login with oauth

src/components/navbar.js, src/helpers.js, src/pages/users.js
forgot to change axios instance baseUrl to env var
=> 🐛 changes instance BaseUrl to env var

src/pages/users.js
Unordered list instead of json strigify
=> ✨ Users displayed in list instead of json string

src/pages/profile/index.js
Now able to update user info from user profile page
=> ✨ Update user info from profile

src/pages/profile/index.js, src/pages/users.js
Displaying majority of backend data on /users page
Displaying most of backend data for project demo
=> ✨ Show users, workflows, questions, answers data

src/components/NewWorkflowModel.js, src/pages/workflow/index.js
Users can now create a new workflow from a dialog pop-up model that does a POST request to the endpoint `/workflows`
=> ✨ Post to workflow from a pop-up modal

src/components/profile/userWorksflows.js, src/components/profile/workflowCard.js
User workflows are now pulled from backend and displayed on frontend.
User data fetched with react hook :-))
=> Backend user workflows

src/components/NewWorkflowModel.js, src/components/profile/userWorksflows.js, src/pages/workflow/index.js
User workflows are now pulled from backend and displayed on frontend.
User data fetched with react hook :-))
=> 🐛 Fixed model page location / post request url

package.json, src/components/EditUserDetailsModel.js, src/components/profile/userInfo.js, src/theme.js, yarn.lock
User can now update company_name, country, phone_num from Profile page
Current user info will be in input field by default so user knows the current info they are about to change
=> ✨ Ability to edit user account info working!

src/components/navbar.js, src/pages/index.js
=> User story1

src/components/dashboard.js, src/components/workflowCard.js, src/pages/profile.js, src/pages/workflow/index.js, src/state/actions.js, src/state/reducers.js
User can now click on a workflow to 
=> Workflow page

src/pages/workflow/index.js, src/state/actions.js
Updating front end to match latest backend pull request
=> 🎨 Removing option_number from post request

src/components/modal.js, src/pages/login.js
Added better Facebook and Google buttons
=> Added better Facebook and Google buttons

src/components/dashboard.js
removed unnecessary components due to user feedback
email, trash, etc
=> removed unnecessary components due to user feedback

package.json, src/components/layout.js, src/pages/index.js, yarn.lock
Added additional styling to match the wireframes. I removed the contact portion of the homepage since there's already so much information on the page. 
I was thinking about changing up the homepage since it contained so much information and split it up into separate pages, but it's already too late to be doing that at this point. 
Mobile Friendly
=> Homepage Styling

package.json, src/components/InfoPopup.js, src/components/addUserWorkflow.js, src/components/layout.js, src/pages/index.js, src/pages/workflows.js, yarn.lock
Info Popup is there to guide new users by explaining how creating flows work.
As more things are implemented in the front end we can add these info popups to help guide users.
Tested locally.. going to have teammates to take a look at it.
=> Info Popup

src/components/modal.js, src/components/utility.js, src/pages/login.js, src/theme.js
=> Updated modal, removed unnecessary code

README.md
=> Updated .env portion
